name: sheikah-icons
base: core20
version: '1.0.0'
summary: Icons with a Sheikah Slate look
description: |
  Snap of the Sheikah icons set

grade: stable
confinement: strict

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Sheikah

parts:
  icons:
    plugin: dump
    source: https://github.com/lvoytek/SheikahIcons/releases/download/$SNAPCRAFT_PROJECT_VERSION/sheikah-icons-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    override-build: |
        snapcraftctl build
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons/Sheikah
        mv * $SNAPCRAFT_PART_INSTALL/share/icons/Sheikah/
    stage:
      - share/icons/Sheikah
